services:
  mysql-master:
    image: mysql:8.0
    restart: always
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./init-master.sql:/docker-entrypoint-initdb.d/init-master.sql

  mysql-slave:
    image: mysql:8.0
    restart: always
    command:
      - --server-id=2
      - --read-only=ON
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --relay-log=mysql-relay-bin
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    volumes:
      - ./init-slave.sql:/docker-entrypoint-initdb.d/init-slave.sql

  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - mysql-master
      - mysql-slave
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST_MASTER=mysql-master
      - DB_HOST_SLAVE=mysql-slave
      - DB_PORT=3306
      - DB_NAME=satelites
      - PORT=8000

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql-master,mysql-slave
      - PMA_VERBOSES=MySQL Master,MySQL Slave
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql-master
      - mysql-slave

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - web

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
